// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddSource(arg1:string,arg2:string,arg3:string):Promise<models.Source>;

export function CreateProject(arg1:string,arg2:string):Promise<models.Project>;

export function CreateSection(arg1:string,arg2:string):Promise<models.Section>;

export function GetProjects():Promise<Array<models.Project>>;

export function GetSections(arg1:string):Promise<Array<models.Section>>;

export function GetSources(arg1:string):Promise<Array<models.Source>>;
