// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSource'](arg1, arg2, arg3);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateSection(arg1, arg2) {
  return window['go']['main']['App']['CreateSection'](arg1, arg2);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSections(arg1) {
  return window['go']['main']['App']['GetSections'](arg1);
}

export function GetSources(arg1) {
  return window['go']['main']['App']['GetSources'](arg1);
}
